site_name: Chaibot Docs
nav:
  - Home: index.md
  - Commands: commands.md
  - Fortnite: fortnite.md
  - Authentication: authentication.md
  - Rocket League: rocketleague.md
  - Setup: setup.md
  - Logs: logs.md
  - Moderation: mod.md
  - Music: music.md
  - Warnings: warnings.md
  - API: api.md
  - TopGG: topgg.md
  - About Dev: about.md
theme:
  name: gitbook
markdown_extensions:
  - meta
